apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-431215
  artifacts:
    #- image: gcr.io/ticketing-dev-431215/auth #always gcr.io/<project id>/<context>
    - image: goodmanisltd/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: goodmanisltd/ticketing-client #always gcr.io/<project id>/< context >
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.ts"
            dest: .
    - image: goodmanisltd/ticketing-ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: goodmanisltd/ticketing-order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: goodmanisltd/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: goodmanisltd/ticketing-payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
